### PR TITLE
Spellchecking, some refinements and citations

### PR DESCRIPTION
**Pull request by matuskalas**
Fixed some:
- Spelling or style issues
- It was mixing US and EU/Commonwealth spelling, so unified to the latter
- Some punctuation
- Smoothened a couple of bits in the text

Added:
- Some citations (It might need a couple more)
- Mention of collab with project 25
- Acknowledgement of ELIXIR

I think it might still need:
- A couple of more citations
- Contributions (or remove this section?)
- Title and short title spelled with only the first letter capital (all words capitalised is a rather US style but not EU)

### CODE REVIEW

**Comment by NuriaQueralt** [comment]
Thank you @matuskalas for your careful review. This is very much appreciated. You cannot see the contributions section because the text is added in another PR that is open. I have added your contribution in it. Please edit it if you miss something via https://github.com/LBolzani/synthetic-health-data-generator/pull/43 PR. I have corrected the (short) titles in #47 PR.

Dear @LBolzani could you accept this PR from Matus? he was key on the metadata model mapping to EDAM. Thank you so much in advance!

**Comment by matuskalas** [comment]
Thank you for the review @NuriaQueralt 🙏🏽 It says it can be merged without conflicts, so maybe good to do before it stops being the case @LBolzani 😊 Million thanks!

I'm not available today to check anything anymore, unfortunately😕

**Comment by matuskalas** [comment]
It should now be ready for merging. I'll continue at the next occassion, falling asleep while writing this ... 😴

**Comment by matuskalas** [comment]
This is how awesome it now looks! 😻
[paper.pdf](https://github.com/LBolzani/synthetic-health-data-generator/files/11894251/paper.pdf) NOW OLD, LOOK BELOW

TODO:

- ~Images do not show in the generated preview (preview.biohackrxiv.org)~ NOW THEY ARE THERE, BUT THE RESOLUTION IS VERY POOR
- Do the Acknowledgements and Contributions sections need a revision? YES, I THINK SO 😊

**Comment by matuskalas** [comment]
I fixed the figures so that they appear in the rendered PDF, but now these problems remain...
[paper.pdf](https://github.com/LBolzani/synthetic-health-data-generator/files/11900131/paper.pdf)

TODO:
- Improve the resolution of all figures, especially figures 3-5
- In figures 3-5 also remove the white sides and make them full-width (adding width=100% didn't help)
- Are all the co-authors now included accordingly in the Contributions section? _E.g._ DC?
- Is it an intention that the Acknowledgements section acknowledges also people who are co-authors?

**Pull request merged**
