### PR TITLE
Added contributions.

### PR DESCRIPTION
**Pull request by NuriaQueralt**
Dear @Basel-Alshaikhdeeb @muhammadshoaib @ljgarcia @gtsueng @LBolzani @SergiAguilo @M-casado could you look at the contributions section and modify it in case you miss something? then @LBolzani can merge this PR no later than this Friday 5th to submit the paper to BioHackrXiv! Thank you all!!

### CODE REVIEW

**Comment by ljgarcia** [comment]
Contributions look good to me. 
Special thanks do not belong to contributions but to acknowledgements. I suggest moving that sentence to the corresponding section.

**Comment by NuriaQueralt** [comment]
Thank you @ljgarcia done!.

**Comment by M-casado** [comment]
LGTM 👍

**Comment by Basel-Alshaikhdeeb** [comment]
Thanks Núria, it looks fine to me

From: Núria Queralt Rosinach ***@***.***>
Date: Wednesday, 3 May 2023 at 21:06
To: LBolzani/synthetic-health-data-generator ***@***.***>
Cc: Basel M.M. ALSHAIKHDEEB ***@***.***>, Mention ***@***.***>
Subject: [LBolzani/synthetic-health-data-generator] Added contributions. (PR #43)

Dear @Basel-Alshaikhdeeb<https://github.com/Basel-Alshaikhdeeb> @muhammadshoaib<https://github.com/muhammadshoaib> @ljgarcia<https://github.com/ljgarcia> @gtsueng<https://github.com/gtsueng> @LBolzani<https://github.com/LBolzani> @SergiAguilo<https://github.com/SergiAguilo> @M-casado<https://github.com/M-casado> could you look at the contributions section and modify it in case you miss something? then @LBolzani<https://github.com/LBolzani> can merge this PR no later than this Friday 5th to submit the paper to BioHackrXiv! Thank you all!!

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/LBolzani/synthetic-health-data-generator/pull/43

Commit Summary

  *   58b88d9<https://github.com/LBolzani/synthetic-health-data-generator/pull/43/commits/58b88d99be42460cb09914e04862f68d17c1edba> Added contributions.

File Changes

(1 file<https://github.com/LBolzani/synthetic-health-data-generator/pull/43/files>)

  *   M bhxiv/paper.md<https://github.com/LBolzani/synthetic-health-data-generator/pull/43/files#diff-1ccefa4ccb22d01acd7f9e7b1ba3e09dc42c101b5be448f1fedb353e12578c5e> (2)

Patch Links:

  *   https://github.com/LBolzani/synthetic-health-data-generator/pull/43.patch
  *   https://github.com/LBolzani/synthetic-health-data-generator/pull/43.diff

**Pull request merged**
