### PR TITLE
MCB - Metadata model changes

### PR DESCRIPTION
**Pull request by M-casado**
Draft PR for the moment, but adding changes here so that it's easier to follow in parallel. 

### Overall changes:
- Changed metadata model (hopefully for the better)

### Future TO-DOs:
- [ ] Modify the Metadata section of the paper.

### CODE REVIEW

**Comment by M-casado** [comment]
@gtsueng, @NuriaQueralt, @SergiAguilo feel free to review and suggest changes. Also note some new comments on the "Comments" column, and that the CSV is rendered correctly by GitHub (hence the version I would recommend to use).

**Comment by M-casado** [comment]
Some new commits to ``main`` have created conflicts with my PR. I am unable to assign reviewers to this PR or to create branches at the main repo, but I was waiting for some feedback before modifying the JSON template and the section in the paper readme.

We need to coordinate better to avoid trampling the efforts disregarding version control.

**Comment by gtsueng** [comment]
@M-casado I've based my mappings off the table with the EDAM updates, but I 100% agree that we need to coordinate better. I think GitHub is NOT the way to go when it comes to working on tables, so I've merged your table with the EDAM updates into a google spreadsheet. I think it might be easier to hash everything out there and then commit the table to GitHub. Nuria will send out the link to the table, and we can go from there.

**Comment by M-casado** [comment]
Agreed, I also think google sheets/docs would be better to coordinate these kind of contributions. Thanks, @gtsueng

**Pull request closed without merging**
